# Generated by Django 4.0.10 on 2025-05-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0005_complaint_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolution_msg',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
