# Generated by Django 4.0.10 on 2025-05-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0006_alter_complaint_resolution_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Request Submitted', max_length=50),
        ),
    ]
